name: score_app
description: A new Flutter application.

version: 1.0.3+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: 3.0.7
  json_annotation: ^3.0.0
  photo_view: ^0.9.0
  shared_preferences: 0.5.4+5
  fluttertoast: ^3.1.3
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - res/images/

